name: Build artifacts

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      sha:
        required: false
        default: ${{ github.sha }}
        type: string

permissions:
  contents: read

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.HQ_VERSION }}
      sha: ${{ env.HQ_SHA }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Set version
        run: |
          echo "HQ_VERSION=${{ inputs.version || 'dev' }}" | tee -a $GITHUB_ENV
      - name: Set sha
        run: |
          echo "HQ_SHA=${{ inputs.sha || github.sha }}" | tee -a $GITHUB_ENV
  build-binaries-x64:
    needs: [ set-env ]
    runs-on: ubuntu-latest
    # Use a container with GLIBC 2.28
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - name: Show GLIBC
        run: ldd --version
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          ref: ${{ needs.set-env.outputs.sha }}
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0

      # Needed for the highs dependency
      - name: Install Clang
        run: yum install clang -y

      - name: Compile
        env:
          HQ_BUILD_VERSION: ${{ needs.set-env.outputs.version }}
        run: cargo build --profile dist --locked

      - name: Compress debuginfo
        run: objcopy --compress-debug-sections=zlib-gnu target/dist/hq

      - name: Prepare archive
        id: archive
        run: |
          export ARCHIVE_NAME=hq-${{ needs.set-env.outputs.version }}-linux-x64.tar.gz
          tar -czvf $ARCHIVE_NAME -C target/dist hq
          echo "archive-name=$ARCHIVE_NAME" >> "$GITHUB_OUTPUT"

      - name: Store archive
        uses: actions/upload-artifact@v5
        with:
          name: archive-x64
          path: ${{ steps.archive.outputs.archive-name }}
