name: Linux tests

on:
  workflow_call:

permissions:
  contents: read

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.95.0
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Test Linux CLI and scheduler
        run: cargo test -p hyperqueue -p tako --lib --locked
      - name: Lint Linux CLI and scheduler
        run: cargo clippy -p hyperqueue -p tako --lib --locked -- -D warnings
